title: 
description:  # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "kgourgou.me" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kostis Gourgoulias # add your name
author-img: me.png # add your photo
about-author: Applied Mathematician, Research Scientist at Babylon Health. # add description
social-twitter: kgourg# add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kgourgou # add your Github handle
social-linkedin: kgourgoulias # add your Linkedin handle
social-email: kgourgoulias+mywebsite@gmail.com # add your Email address

# Disqus
discus-identifier: disqus_LZJ2gyisrv # add your discus identifier


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
