# Site settings
title: Kostis Gourgoulias
email: kgourgoulias+mywebsite@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: localhost:4000 # the base hostname & protocol for your site



# Sidebar settings
description: 

# Social icons
#facebook: username
linkedin: kgourgoulias
github: kgourgou
deviantart: username
codepen: username


# Build settings
markdown: kramdown
